---
language: python
services: docker

env:
  global:
    - ROLE_NAME: supervisor
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian9

    - MOLECULE_DISTRO: ubuntu1804
      MOLECULE_PLAYBOOK: playbook-inet-http.yml

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test
